### ISSUE TITLE
[build] replace isort with ruff in pre-commit

### ISSUE THREAD

**Issue by TheEpic-dev** [djangosocialteam/djangosocial#3]
As `ruff` can do automatic import sorting, `isort` is an unnecessary dependency.

- [ ] delete `isort` from the `pre-commit-config.yaml` file.
- [ ] delete the `[tool.isort]` section from `django/pyproject.toml`
- [ ] add `ruff` to pre-commit
- [ ] configure `ruff`... auto-fix sorting, and not sure what else

**Comment by marksweb** [comment]
I've got a set of ruff rules that I quite like. I could include these in the project?

https://gist.github.com/marksweb/6da1c14698de4fe62d89b13122f5b2d5

**Comment by TheEpic-dev** [comment]
> I've got a set of ruff rules that I quite like. I could include these in the project?
> 
> https://gist.github.com/marksweb/6da1c14698de4fe62d89b13122f5b2d5

I did add a bunch of  `ruff` rules to `pyproject.toml` already: https://github.com/djangosocialteam/djangosocial/blob/main/django/pyproject.toml#L34

But they are always open to improvements. The more pressing matter is integration with `pre-commit`.

**Comment by marksweb** [comment]
What about python upgrade and django upgrade while I'm in the config?

**Comment by TheEpic-dev** [comment]
Python 3.12? That was on my todo list, so sure :)
Django itself is currently 4.2.6, so no real reason to upgrade now, I think?

**Comment by marksweb** [comment]
Oh no, there's hooks that can upgrade the python and django code to match the current version we're using - I'll include it
